### ISSUE TITLE
Investigate Chain of Hindsight for fine-tuning

### ISSUE THREAD

**Issue by 0x000011b** [PygmalionAI/data-toolbox#12]
[Paper](https://arxiv.org/abs/2302.02676), [code](https://github.com/lhao499/CoH), [summary in the form of a Twitter thread](https://nitter.net/haoliuhl/status/1630696378325413888). [Claims to beat](https://nitter.net/pic/orig/media%2FFqFlxx_aYAEMcTp.jpg) supervised fine-tuning (what we're currently doing) and RLHF (what we're not doing due to data and compute constraints at the moment).

If we're to faithfully follow the paper, we'll need multiple generations for a given prompt. [RankGen](https://github.com/martiansideofthemoon/rankgen) + the existing models can help us generate synthetic data for this.

**Comment by AlpinDale** [comment]
I don't think we'll need to do this as there are better alternatives now. [SelFee](https://kaistai.github.io/SelFee/) is promising, for one.

**Comment by TearGosling** [comment]
An old issue - closing for now.
