### ISSUE TITLE
Publish/Share the share_gpt.json file 

### ISSUE THREAD

**Issue by manyoso** [PygmalionAI/data-toolbox#13]
Hi, based on your toolbox it seems pygmallion has the sharegpt dataset. Since the get operation for this is now closed can you share the data you gathered for other model generation research purposes? Thanks!

**Comment by 0x000011b** [comment]
Hello! I'm unsure what the license says regarding redistribution so I'd rather not link it directly to avoid possible problems, but if you go on HuggingFace datasets and search for `vicuna` you'll find several ShareGPT scrapes.
