### ISSUE TITLE
Always yield the first messge of each thread as an independent thread

### ISSUE THREAD

**Issue by silverriver** [PygmalionAI/data-toolbox#30]
https://github.com/PygmalionAI/data-toolbox/blob/21687af22a849fca5fd2fa2d890f0911249fe4d4/toolbox/datasets/rp_forums.py#L61C49-L61C49

if the thread has the following message:
m1
m2
m3
m4

The current code with yield two threads:
m1
and
m2, m3, m4

**Comment by TearGosling** [comment]
Closing due to bug being fixed in #31.
